id: Messaging
key: Messaging
name: Messaging
description: Provides a simple messaging service based on the Twitter API.
author_name: "Endevver, LLC"
author_link: http://www.endevver.com/
plugin_class: TwitterAPI::Plugin
schema_version: 2
version: 1.0.1

config_settings:
    TwitterAPIScript:
        default: twitter.cgi

object_types:
    tw_favorite: Melody::Favorite
    tw_follower: Melody::Follower
    tw_message:  Melody::Message

callbacks:
    MT::Author::post_remove: Melody::API::Twitter::Callbacks::author_post_remove

applications:
    cms:
        menus:
            manage:messages:
                label: 'Messages'
                order: 9000
                mode: list_messages
                view: system
                permission: administer
            system:messages:
                label: 'Messages'
                order: 1100
                mode: list_messages
                permission: administer
        methods:
            list_messages:  TwitterAPI::Plugin::list
            hide_message:   TwitterAPI::Plugin::hide
            show_message:   TwitterAPI::Plugin::show
    twitter_api:
        handler: 'Melody::API::Twitter'

widgets:
    messaging:
        label: 'Messaging'
        template: 'dashboard_widget.mtml'

list_actions:
    tw_message:
        delete:
            label: 'Delete'
            code: TwitterAPI::Plugin::delete
            permission: administer

tags:
    block:
        Messages: TwitterAPI::Tags::messages
    function:
        MessageID: TwitterAPI::Tags::message_id
        MessageText: TwitterAPI::Tags::message_text
        MessageGeoLong: TwitterAPI::Tags::message_geo_long
        MessageGeoLat: TwitterAPI::Tags::message_geo_lat
        MessageAuthorID: TwitterAPI::Tags::message_author_id
        MessageDate: TwitterAPI::Tags::message_date

