id: Messaging
key: Messaging
name: Messaging
description: Provides a simple messaging service based on the Twitter API.
author_name: "Endevver, LLC"
author_link: http://www.endevver.com/
plugin_class: TwitterAPI::Plugin
schema_version: 2
version: 1.0.1

config_settings:
    TwitterAPIScript:
        default: twitter.cgi

object_types:
    tw_favorite: Melody::Favorite
    tw_follower: Melody::Follower
    tw_message:  Melody::Message

callbacks:
    MT::Author::post_remove: Melody::API::Twitter::Callbacks::author_post_remove

applications:
    cms:
        menus:
            manage:messages:
                label: 'Messages'
                order: 9000
                mode: list_messages
                view: system
            system:messages:
                label: 'Messages'
                order: 1100
                mode: list_messages
        methods:
            list_messages:  TwitterAPI::Plugin::list
    twitter_api:
        handler: 'Melody::API::Twitter'

widgets:
    messaging:
        label: 'Messaging'
        template: 'dashboard_widget.mtml'

