id: Messaging
key: Messaging
name: Messaging
version: 1.0.13
description: Provides a simple messaging service based on the Twitter API.
author_name: "Endevver, LLC"
author_link: http://www.endevver.com/
# The plugin class causes *config_template to fail when loading the Plugin 
# Settings screen?
#    Cannot find column 'defaults' for class 'MT::Template' at lib/MT/Plugin.pm line 194 
#plugin_class: Messaging::Plugin
schema_version: 3
static_version: 8

config_settings:
    MessagingScript:
        default: msg.cgi

object_types:
    tw_favorite: Messaging::Favorite
    tw_follower: Messaging::Follower
    tw_message:  Messaging::Message

callbacks:
    MT::Author::post_remove: Messaging::Twitter::Callbacks::author_post_remove

applications:
    cms:
        menus:
            manage:messages:
                label: 'Messages'
                order: 9000
                mode: list_messages
                view: system
                permission: administer
            system:messages:
                label: 'Messages'
                order: 1100
                mode: list_messages
                permission: administer
        methods:
            list_messages:  Messaging::Plugin::list
            hide_message:   Messaging::Plugin::hide
            show_message:   Messaging::Plugin::show
    messaging_api:
        handler: 'Messaging::Twitter'

widgets:
    messaging:
        label: 'Messaging'
        template: 'dashboard_widget.mtml'
        code: Messaging::Plugin::dashboard_widget
        singular: 1

list_actions:
    tw_message:
        delete:
            label: 'Delete'
            code: Messaging::Plugin::delete
            permission: administer

tags:
    block:
        Messages:        Messaging::Tags::messages
        MessageTags:     Messaging::Tags::message_tags
    function:
        MessagingAPIURL: Messaging::Tags::messaging_api_url
        MessageID:       Messaging::Tags::message_id
        MessageText:     Messaging::Tags::message_text
        MessageGeoLong:  Messaging::Tags::message_geo_long
        MessageGeoLat:   Messaging::Tags::message_geo_lat
        MessageAuthorID: Messaging::Tags::message_author_id
        MessageDate:     Messaging::Tags::message_date

blog_config_template: 
    code: Messaging::Plugin::settings

settings:
    republish_templates:
        default: '0'
        scope: blog

